#!/usr/bin/env python3
"""
Generate docker-compose.yml and docker-compose.aws.yml from config.yaml.

Workflow:
    1. Edit  network.num_workers  in config.yaml
    2. Run   python scripts/generate_compose.py
    3. Run   docker compose up --build
"""
import os
import yaml

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load_config() -> dict:
    with open(os.path.join(PROJECT_ROOT, "config.yaml")) as f:
        return yaml.safe_load(f)


_HEALTHCHECK = (
    '      test: ["CMD-SHELL", "python -c \\"import urllib.request; '
    'urllib.request.urlopen(\'http://localhost:5000/peers\')\\""]'
)


def write_local_compose(num_workers: int) -> None:
    """
    Generate docker-compose.yml for local single-machine development.

    Uses string templating (instead of yaml.dump) so that the healthcheck
    test is rendered as an inline flow sequence, which IDE schema validators
    accept without warnings.
    """
    worker_blocks = []
    for i in range(num_workers):
        worker_blocks += [
            "",
            f"  worker_{i}:",
            "    build:",
            "      context: .",
            "      dockerfile: Dockerfile.worker",
            "    environment:",
            f"      - WORKER_ID={i}",
            f"      - TOTAL_WORKERS={num_workers}",
            f"      - MY_HOST=worker_{i}",
            "    depends_on:",
            "      registry:",
            "        condition: service_healthy",
            "    volumes:",
            f"      - ./data/femnist/worker_{i}:/app/data/femnist",
            "    networks:",
            "      - fl_net",
        ]

    lines = [
        'version: "3.8"',
        "",
        "services:",
        "",
        "  registry:",
        "    build:",
        "      context: .",
        "      dockerfile: Dockerfile.registry",
        "    ports:",
        '      - "5000:5000"',
        "    networks:",
        "      - fl_net",
        "    healthcheck:",
        _HEALTHCHECK,
        "      interval: 5s",
        "      timeout: 3s",
        "      retries: 10",
    ] + worker_blocks + [
        "",
        "networks:",
        "  fl_net:",
        "    driver: bridge",
        "",
    ]

    path = os.path.join(PROJECT_ROOT, "docker-compose.yml")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  docker-compose.yml        ({num_workers} workers)")


def write_aws_compose(num_workers: int, grpc_port: int) -> None:
    """
    Generate docker-compose.aws.yml for AWS EC2 deployment.

    Written as a string template because yaml.dump does not support YAML
    anchors (&worker-base / <<: *worker-base) needed for DRY service definitions.
    Each worker gets a distinct host port: grpc_port + worker_id.
    """
    header = [
        "# docker-compose.aws.yml — generated by scripts/generate_compose.py",
        "#",
        "# OPTION A — single EC2 instance:",
        "#   EC2_PUBLIC_IP=<ip> docker compose -f docker-compose.aws.yml up -d",
        "#",
        "# OPTION B — one EC2 instance per worker:",
        "#   Registry node:",
        "#     docker compose -f docker-compose.aws.yml up registry",
        "#   Each worker node (e.g. worker_0):",
        "#     REGISTRY_EC2_IP=<ip-registry> EC2_PUBLIC_IP=<ip-node> \\",
        "#     WORKER_ID=0 MY_HOST=<ip-node> docker compose -f docker-compose.aws.yml up worker_0",
        "#",
        f"# AWS PREREQUISITES: Security Group open on port 5000 (registry HTTP) "
        f"and {grpc_port}–{grpc_port + num_workers - 1} (gRPC workers)",
        "",
        'version: "3.8"',
        "",
        "x-worker-base: &worker-base",
        "  build:",
        "    context: .",
        "    dockerfile: Dockerfile.worker",
        "",
        "services:",
        "",
        "  registry:",
        "    build:",
        "      context: .",
        "      dockerfile: Dockerfile.registry",
        "    ports:",
        '      - "5000:5000"',
        "    healthcheck:",
        _HEALTHCHECK,
        "      interval: 5s",
        "      timeout: 3s",
        "      retries: 10",
    ]

    worker_blocks = []
    for i in range(num_workers):
        # Each worker maps a unique host port to the same container port (grpc_port),
        # so that multiple workers on the same EC2 instance don't collide.
        host_port = grpc_port + i
        worker_blocks += [
            "",
            f"  worker_{i}:",
            "    <<: *worker-base",
            "    volumes:",
            f"      - ./data/femnist/worker_{i}:/app/data/femnist",
            "    environment:",
            f"      - WORKER_ID={i}",
            f"      - TOTAL_WORKERS={num_workers}",
            f"      - MY_HOST=${{EC2_PUBLIC_IP:-worker_{i}}}",
            f"      - REGISTRY_URL=http://${{REGISTRY_EC2_IP:-registry}}:5000",
            "    ports:",
            f'      - "{host_port}:{grpc_port}"',
            "    depends_on:",
            "      registry:",
            "        condition: service_healthy",
        ]

    path = os.path.join(PROJECT_ROOT, "docker-compose.aws.yml")
    with open(path, "w") as f:
        f.write("\n".join(header + worker_blocks) + "\n")
    print(f"  docker-compose.aws.yml    ({num_workers} workers, ports {grpc_port}–{grpc_port + num_workers - 1})")


def main():
    cfg = _load_config()
    num_workers: int = cfg["network"]["num_workers"]
    grpc_port: int = cfg["network"]["grpc_port"]

    print(f"Generating compose files — {num_workers} workers, gRPC base port {grpc_port} ...")
    write_local_compose(num_workers)
    write_aws_compose(num_workers, grpc_port)
    print("Done. Run: docker compose up --build")


if __name__ == "__main__":
    main()
